[Paths]

# temporary foldler that saved decoded APK files.
STORE_APK_PATH = /home/ApkScanner/ApkScannerLibrary/temp/apk_temp  

# temporary foldler that saved decoded files.
DECODE_APK_PATH = /home/ApkScanner/ApkScannerLibrary/temp/decode_temp  

LIBRARY_PATH = /home/ApkScanner/ApkScannerLibrary/APK/VirusShare_Android_APK_2022-2
RESULT_PATH = /home/ApkScanner/result
STATISTICS_PATH = /home/ApkScanner/statistics

[Files]
DOMAIN_FILE_NAME = %(timestamp)%_%(filename)%_url.csv
HAS_IPV6_FILE_NAME = has_ipv6_domain_ipv6.csv
NON_EXISTENT_FILE_NAME = Non_existent_domain_ipv6.csv
INDEX_LIST_FILE_NAME = apk_scan_index_list.csv
ORDER_FILE_NAME = merged_unique_domains.csv
STATISTICS_APK_FILE_NAME = apk_files_list.csv

[Settings]
SKIP_DIRS = original
NAMESERVERS = 8.8.8.8,8.8.4.4
SCAN_EXTENSIONS = .xml,.smali
ACCEPT_APK_EXTENSION = .apk,.xapk

[Logging]

# logs foldler.
LOG_DIRECTORY = /home/ApkScanner/logs

# logs file name
LOG_FILENAME = %(asctime)s_apk_scanner.logs  

# timestamp of logs file name format.
LOG_FORMAT = %(asctime)s - %(filename)s - %(levelname)s - %(message)s

# console logger level (useless)
CONSOLE_LOG_LEVEL = DEBUG

# logs files logger level
FILE_LOG_LEVEL = DEBUG
